ERROR 2020-02-29 13:36:11,182   499ms eporting Portal Logger GetSupplierOrders  - GetSupplierOrders ==> SP = LMNS_GetSupplierOrders ==> supplier = 20799
System.NullReferenceException: Object reference not set to an instance of an object.
   at LMNS.Repositories.Dal.ConnectionStringByCompany(String companyName) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 221
   at LMNS.Repositories.Dal.GetConnectionString() in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 19
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 77
   at TestPortal.Models.Order.GetSupplierOrders(String supplier) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Order.cs:line 26
ERROR 2020-02-29 16:54:32,744   204ms eporting Portal Logger GetOrderDetails    - OrderDetails ==> SP = LMNS_GetOrderDetails ==> ord = 114553
System.Data.SqlClient.SqlException (0x80131904): Procedure or function 'LMNS_GetSupplierOrders' expects parameter '@supName', which was not supplied.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 87
   at TestPortal.Models.Order.GetOrderDetails(Int32 orderID) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Order.cs:line 51
ClientConnectionId:a6750b26-1ff6-4e0a-bf03-e00e71e59c4c
Error Number:201,State:4,Class:16
ERROR 2020-03-02 17:41:10,038   253ms eporting Portal Logger etProdRevisionList - GetProdRevisionList ==> SP = LMNS_GetProductTestsList ==> PART [key] = 133027 ==> @revId = 0
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at TestPortal.Models.Revision.GetProdRevisionList(Int32 prodId, String revId) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Revision.cs:line 35
ERROR 2020-03-02 18:20:39,116   187ms eporting Portal Logger etProdRevisionList - GetProdRevisionList ==> SP = LMNS_GetProductTestsList ==> PART [key] = 133027 ==> @revId = 0
System.FormatException: Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at TestPortal.Models.Revision.GetProdRevisionList(Int32 prodId, String revId) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Revision.cs:line 35
ERROR 2020-03-02 18:35:58,314   142ms eporting Portal Logger etProdRevisionList - GetProdRevisionList ==> SP = LMNS_GetProductTestsList ==> PART [key] = 133027 ==> @revId = A
System.Data.SqlClient.SqlException (0x80131904): Error converting data type nvarchar to bigint.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at TestPortal.Models.Revision.GetProdRevisionList(Int32 prodId, String revId) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Revision.cs:line 35
ClientConnectionId:37a44840-9c3f-4d9d-89c5-ddafc88d65b9
Error Number:8114,State:5,Class:16
ERROR 2020-03-02 18:36:31,264 33093ms eporting Portal Logger etProdRevisionList - GetProdRevisionList ==> SP = LMNS_GetProductTestsList ==> PART [key] = 133027 ==> @revId = A
System.Data.SqlClient.SqlException (0x80131904): Error converting data type nvarchar to bigint.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at TestPortal.Models.Revision.GetProdRevisionList(Int32 prodId, String revId) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Revision.cs:line 35
ClientConnectionId:5b64455e-5b81-406b-b303-a575206d6ea0
Error Number:8114,State:5,Class:16
ERROR 2020-03-02 18:39:45,010 226839ms eporting Portal Logger etProdRevisionList - GetProdRevisionList ==> SP = LMNS_GetProductTestsList ==> PART [key] = 133027 ==> @revId = A
System.Data.SqlClient.SqlException (0x80131904): Error converting data type nvarchar to bigint.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at TestPortal.Models.Revision.GetProdRevisionList(Int32 prodId, String revId) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Revision.cs:line 35
ClientConnectionId:2abdb988-2ac5-4dc1-9f48-ea754f59dd93
Error Number:8114,State:5,Class:16
ERROR 2020-03-02 18:47:10,168   143ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-02 18:49:51,943 161919ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-02 18:50:34,236 204211ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-02 18:51:04,721 234696ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-02 18:51:55,851 285827ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-02 18:51:59,682 289657ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-02 18:52:40,987 330962ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-02 18:52:53,953 343928ms eporting Portal Logger GetOrderItems      - GetOrderItems ==> SP = LMNS_GetOrderItems ==> ORD [key] = 114553
System.IndexOutOfRangeException: REV
   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at TestPortal.Models.Product.GetOrderItems(Int32 parentRowKey) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Product.cs:line 50
ERROR 2020-03-04 15:40:15,714   188ms eporting Portal Logger GetSupplierOrders  - GetSupplierOrders ==> SP = LMNS_GetSupplierOrders ==> supplier = 22149
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 78
   at TestPortal.Models.Order.GetSupplierOrders(String supplier) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\Order.cs:line 26
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
ERROR 2020-03-13 12:13:57,128   554ms eporting Portal Logger UserLogin          - UserLogin ==> SP = LMNS_UserLogin ==> @email = kereng@radion.com @pass = 1234
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 78
   at TestPortal.Models.AppUser.UserLogin() in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\AppUser.cs:line 29
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
DEBUG 2020-03-19 13:01:25,878   600ms eporting Portal Logger CreateResultApi    - FunctionName = CreateResultApiExceptionMsg = Object reference not set to an instance of an object.
DEBUG 2020-03-19 13:02:06,461 41183ms eporting Portal Logger CreateResultApi    - FunctionName = CreateResultApiExceptionMsg = Object reference not set to an instance of an object.
DEBUG 2020-03-19 13:09:48,135   165ms eporting Portal Logger CreateResultApi    - FunctionName = CreateResultApiExceptionMsg = Object reference not set to an instance of an object.
DEBUG 2020-03-19 13:13:50,410   130ms eporting Portal Logger CreateResultApi    - FunctionName = CreateResultApiExceptionMsg = Object reference not set to an instance of an object.
DEBUG 2020-03-19 13:14:06,424 16143ms eporting Portal Logger CreateResultApi    - FunctionName = CreateResultApiExceptionMsg = Object reference not set to an instance of an object.
ERROR 2020-03-20 12:00:41,725   554ms eporting Portal Logger UserLogin          - UserLogin ==> SP = LMNS_UserLogin ==> @email = moshe@radion.co.il @pass = 1234
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 78
   at TestPortal.Models.AppUser.UserLogin() in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\AppUser.cs:line 29
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
DEBUG 2020-03-20 12:01:24,964 43793ms eporting Portal Logger CreateResultApi    - FunctionName = CreateResultApiExceptionMsg = Object reference not set to an instance of an object.
ERROR 2020-03-21 13:26:23,567   521ms eporting Portal Logger UserLogin          - UserLogin ==> SP = LMNS_UserLogin ==> @email = moshe@radion.co.il @pass = 1234
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 78
   at TestPortal.Models.AppUser.UserLogin() in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\AppUser.cs:line 29
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
ERROR 2020-03-23 22:18:15,073   579ms eporting Portal Logger UserLogin          - UserLogin ==> SP = LMNS_UserLogin ==> @email = moshe@radion.co.il @pass = 1234
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 78
   at TestPortal.Models.AppUser.UserLogin() in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\AppUser.cs:line 29
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
DEBUG 2020-03-25 09:28:50,336  3229ms eporting Portal Logger CreateResultApi    - FunctionName = CreateResultApiExceptionMsg = '100' is an unexpected token. The expected token is '"' or '''. Line 28, position 70.
ERROR 2020-03-25 21:17:06,420   287ms eporting Portal Logger UserLogin          - UserLogin ==> SP = LMNS_UserLogin ==> @email = osnat@chrom.co.il @pass = 1234
System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: Named Pipes Provider, error: 40 - Could not open a connection to SQL Server) ---> System.ComponentModel.Win32Exception (0x80004005): The network path was not found
   at System.Data.SqlClient.SqlInternalConnectionTds..ctor(DbConnectionPoolIdentity identity, SqlConnectionString connectionOptions, SqlCredential credential, Object providerInfo, String newPassword, SecureString newSecurePassword, Boolean redirectedUserInstance, SqlConnectionString userConnectionOptions, SessionData reconnectSessionData, DbConnectionPool pool, String accessToken, Boolean applyTransientFaultHandling, SqlAuthenticationProviderManager sqlAuthProviderManager)
   at System.Data.SqlClient.SqlConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at LMNS.Repositories.Dal.GetRecordSet(String spName, SqlParameter[] p) in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Repositories\Dal.cs:line 78
   at TestPortal.Models.AppUser.UserLogin() in H:\DEV\EfectiveImlemantation\TestPortal\TestPortal\Models\AppUser.cs:line 29
ClientConnectionId:00000000-0000-0000-0000-000000000000
Error Number:53,State:0,Class:20
